CREATE TABLE thing
(
id   VARCHAR(100) NOT NULL,
name VARCHAR(100) NOT NULL
);

--;;

CREATE TABLE other_thing
(
id       VARCHAR(100) NOT NULL,
name     VARCHAR(100) NOT NULL,
thing_id VARCHAR(100) NOT NULL
);
