CREATE TABLE thing
(
id   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

CREATE TABLE other_thing
(
id       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name     VARCHAR(100),
thing_id INT NOT NULL
);
